### ISSUE TITLE
Can I use blockbench

### ISSUE THREAD

**Issue by Herewegoagainandagain** [Gamepiaynmo/CustomPlayerModel#27]
If so, what format should I use?

**Comment by ghost** [comment]
Hi, yes you can use blockbench. use the bedrock entity with box UV (not per-face UV).

if you want to use it for the legacy version of the mod (1.12), you'll need a plugin that is on the discord (https://discord.gg/aZBytmT6),

if you want to use it for the remake version (1.16), you export your model as bedrock geometry, then you'll need to set up other files to make it work (there are examples on the discord if you want)

also 2 things : this mod is kind of abendoned by the author (you're lucky i have notification on. i don't know why i have github notification on). so it is better if you ask question on the discord.
also, a lot of people mixe together custom player model and customizable player model. i guess you know know which one you are using because you are on the github and not the discord, but I just want to make sure.

**Comment by Herewegoagainandagain** [comment]
can i keep contacting you in case if I need more help?

**Comment by ghost** [comment]
yes,  tho I think it would be easier to do it in Discord (on the CPM discord server) (my username is zerustu)
